---
- name: Create hosts entry for environment - {{ compose_magento_project_name }}
  lineinfile:
    line: "{{ compose_magento_project_gateway }} {{ compose_magento_project_domain }}"
    path: "{{ compose_magento_hosts_file }}"
    regexp: "{{ compose_magento_project_gateway }}.*"
    state: present
  tags:
    - lineinfile
    - hosts
  when: compose_magento_hosts_file is defined and compose_magento_hosts_file != ""
  become: true
